# Install via CocoaPods pointing at current local codebase

platform :osx, '10.8'
use_frameworks!

target 'RKMacOSX' do
  pod 'RestKit/Network', :path => '../../'
  pod 'RestKit/ObjectMapping', :path => '../../'
  pod 'RestKit/CoreData', :path => '../../'
end

