platform :ios, '8.0'
use_frameworks!

# Install via CocoaPods pointing at current local codebase
target 'RKTwitter' do
  pod 'RestKit/Network', :path => '../../'
  pod 'RestKit/ObjectMapping', :path => '../../'
end
