platform :ios, '8.0'
use_frameworks!

def import_pods
  pod 'RestKit/Network', :path => '../../'
  pod 'RestKit/ObjectMapping', :path => '../../'
  pod 'RestKit/CoreData', :path => '../../'
end

# Install via CocoaPods pointing at current local codebase
target 'RKTwitterCoreData' do
  import_pods
end

target 'Generate Seed Database' do
  import_pods
end
